server:
  port: ${PORT:8080}

spring:
  application:
    name: icqa_shein

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:icqa_db}
        format_sql: true
    show-sql: ${SHOW_SQL:false}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}

app:
  security:
    jwt:
      secret: ${JWT_SECRET:CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32+_CHARS_123456}
      access-token-minutes: ${JWT_ACCESS_TOKEN_MINUTES:240}